//product suggestions can be added here ... 
let suggestions = [
    "TriFold Men's Wallet - Black",
    "TriFold Men's Wallet - Brown",
    "BiFold Men's Wallet - Black",
    "BiFold Men's Wallet - Brown",
    "Slim Men's Wallet - Brown",
    "Minimalist Card Holder - Black",
    "Minimalist Card Holder - Brown",
    "Money Clip Men's Wallet - Black",
    "Money Clip Men's Wallet - Brown",
    "Leather Wallet - Product",
    "Men's Wallet - Product",
    "Card Holder - Product",
    "Products Page",
    "About Page",
    "Contributors",
    "Testimonials",
    "Customer Review",
    "Contact Us",
    "How to contact for issue",
    "How to repote a issue",
]